/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "outline-variant": "#e2bfb2",
        "on-tertiary-fixed": "#001d31",
        "surface-container-lowest": "#ffffff",
        "on-surface-variant": "#5a4138",
        "primary-container": "#cc4900",
        "primary": "#a33900",
        "secondary": "#006e2d",
        "error": "#ba1a1a",
        "on-primary-container": "#fffbff",
        "tertiary-fixed": "#cce5ff",
        "on-secondary-fixed": "#002109",
        "surface-container-high": "#e2e7ff",
        "inverse-primary": "#ffb599",
        "background": "#faf8ff",
        "surface-variant": "#dae2fd",
        "surface-bright": "#faf8ff",
        "on-secondary-fixed-variant": "#005320",
        "surface-tint": "#a73a00",
        "on-secondary-container": "#007230",
        "on-background": "#131b2e",
        "on-primary-fixed-variant": "#7f2b00",
        "tertiary": "#006194",
        "on-error": "#ffffff",
        "tertiary-container": "#007bb9",
        "outline": "#8e7166",
        "surface-container-low": "#f2f3ff",
        "on-tertiary-container": "#fdfcff",
        "surface": "#faf8ff",
        "on-tertiary-fixed-variant": "#004b73",
        "on-primary": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-surface": "#131b2e",
        "inverse-on-surface": "#eef0ff",
        "tertiary-fixed-dim": "#93ccff",
        "secondary-fixed-dim": "#62df7d",
        "surface-container": "#eaedff",
        "on-primary-fixed": "#370e00",
        "surface-container-highest": "#dae2fd",
        "primary-fixed": "#ffdbce",
        "surface-dim": "#d2d9f4",
        "inverse-surface": "#283044",
        "secondary-fixed": "#7ffc97",
        "on-secondary": "#ffffff",
        "secondary-container": "#7cf994",
        "error-container": "#ffdad6",
        "primary-fixed-dim": "#ffb599",
        "on-error-container": "#93000a",
        stellar: {
          50: '#f0f9ff',
          100: '#e0f2fe',
          400: '#38bdf8',
          500: '#0ea5e9',
          600: '#0284c7',
          900: '#0c4a6e',
        },
        cavos: {
          500: '#8b5cf6',
          600: '#7c3aed',
        },
        amber: {
          400: '#fbbf24',
          500: '#f59e0b',
          600: '#d97706',
        }
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        margin: "2rem",
        gutter: "1.5rem",
        "gutter-mobile": "1rem",
        "space-xl": "2rem",
        "space-md": "1rem",
        "margin-mobile": "1rem",
        "space-lg": "1.5rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem"
      },
      fontFamily: {
        "label-sm": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "code-sm": ["JetBrains Mono", "monospace"],
        "body-sm": ["Plus Jakarta Sans", "sans-serif"],
        "metric-xl": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "metric-md": ["Plus Jakarta Sans", "sans-serif"],
        sans: ["Plus Jakarta Sans", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"]
      },
      fontSize: {
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
        "headline-md": ["22px", { lineHeight: "28px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "display-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "headline-sm": ["18px", { lineHeight: "24px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "display-lg-mobile": ["30px", { lineHeight: "38px", letterSpacing: "-0.025em", fontWeight: "700" }],
        "code-sm": ["12px", { lineHeight: "16px", letterSpacing: "0em", fontWeight: "500" }],
        "body-sm": ["13px", { lineHeight: "18px", letterSpacing: "0em", fontWeight: "400" }],
        "metric-xl": ["36px", { lineHeight: "44px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "body-md": ["14px", { lineHeight: "20px", letterSpacing: "-0.005em", fontWeight: "400" }],
        "headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "-0.025em", fontWeight: "700" }],
        "metric-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
}
